name: Deploy to Portainer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Portainer webhook
        uses: distributhor/portainer-webhook@v2
        with:
          webhook: ${{ secrets.PORTAINER_WEBHOOK }}
